### ISSUE TITLE
InvalidArgumentError (see above for traceback): Saw a non-null label (index >= n um_classes - 1) following a null label, batch: 13 num_classes: 95 labels: 29

### ISSUE THREAD

**Issue by vinayakkailas** [MaybeShewill-CV/CRNN_Tensorflow#100]
i have 94 ascii characters in my order_map. While running training i am getting this error
Traceback (most recent call last):
  File "train_shadownet.py", line 177, in <module>
    train_shadownet(args.dataset_dir, args.weights_path)
  File "train_shadownet.py", line 127, in train_shadownet
    [optimizer, cost, sequence_dist, decoded, input_labels, merge_summary_op])
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\c
lient\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\c
lient\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\c
lient\session.py", line 1355, in _do_run
    options, run_metadata)
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\c
lient\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null lab
el (index >= num_classes - 1) following a null label, batch: 13 num_classes: 95
labels: 29
         [[Node: CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_output
s_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost
/replica:0/task:0/device:CPU:0"](shadow/LSTMLayers/transpose_time_major, shuffle
_batch/control_dependency_1, shuffle_batch/control_dependency_2, CTCBeamSearchDe
coder/sequence_length)]]

Caused by op 'CTCLoss', defined at:
  File "train_shadownet.py", line 177, in <module>
    train_shadownet(args.dataset_dir, args.weights_path)
  File "train_shadownet.py", line 65, in train_shadownet
    cost = tf.reduce_mean(tf.nn.ctc_loss(labels=input_labels, inputs=net_out, se
quence_length=25*np.ones(32)))
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\o
ps\ctc_ops.py", line 158, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\o
ps\gen_ctc_ops.py", line 231, in _ctc_loss
    name=name)
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\f
ramework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\f
ramework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "C:\Users\vinayak\Documents\vinayak\lib\site-packages\tensorflow\python\f
ramework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-
access

InvalidArgumentError (see above for traceback): Saw a non-null label (index >= n
um_classes - 1) following a null label, batch: 13 num_classes: 95 labels: 29
         [[Node: CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_output
s_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost
/replica:0/task:0/device:CPU:0"](shadow/LSTMLayers/transpose_time_major, shuffle
_batch/control_dependency_1, shuffle_batch/control_dependency_2, CTCBeamSearchDe
coder/sequence_length)]]

**Comment by vinayakkailas** [comment]
I found my mistake, i ahve 95 charecters, so i had to give 96 as the num_classes
