### ISSUE TITLE
can't multiply sequence by non-int of type 'NoneType'

### ISSUE THREAD

**Issue by CMWENLIU** [MaybeShewill-CV/CRNN_Tensorflow#134]
Did any one has this problem?  Could anyone help me about this? Thanks.
When I run the command line for test model. This is happened.
`Traceback (most recent call last):
  File "tools/test_shadownet.py", line 200, in <module>
    test_shadownet(args.dataset_dir, args.weights_path, args.is_recursive, args.num_threads, args.num_classes)
  File "tools/test_shadownet.py", line 71, in test_shadownet
    num_threads=num_threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/input.py", line 922, in batch
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/input.py", line 708, in _batch
    _enqueue(queue, tensor_list, num_threads, enqueue_many, keep_input)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/input.py", line 683, in _enqueue
    control_flow_ops.no_op)] * threads
TypeError: can't multiply sequence by non-int of type 'NoneType'
`

**Comment by mdbenito** [comment]
You need to set the number of classes to 37 using `--num-classes`. I should've documented that in the last PR, or set the default value.

**Comment by CMWENLIU** [comment]
This problem fixed.
Thanks!

**Comment by mdbenito** [comment]
@MaybeShewill-CV This issue could be closed
