### ISSUE TITLE
Is the ckpt wrong?

### ISSUE THREAD

**Issue by Crazlion** [MaybeShewill-CV/CRNN_Tensorflow#168]
INFO: 10-11 02:52:46: tf_logging.py:115 * 140680814909184 Restoring parameters from ./model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
2018-10-11 02:52:46.563415: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key shadow/batch_normalization/beta not found in checkpoint

**Comment by MaybeShewill-CV** [comment]
@Crazlion Maybe caused by the tensorflow version problem. The uploaded ckpt is trained under tf 1.3

**Comment by Crazlion** [comment]
but I used the docker/cpu/dockerfile to build the docker,that need tensorflow/tensorflow:1.10.0-py3

**Comment by MaybeShewill-CV** [comment]
@Crazlion The docker file is built after the ckpt uploaded so the tf version is 1.10

**Comment by Crazlion** [comment]
我将git转到原来的版本，使用3999的检查点跑成功了，非常的感谢！

**Comment by Crazlion** [comment]
> @Crazlion The docker file is built after the ckpt uploaded so the tf version is 1.10

我将git切换到前面的版本，使用原来的模型运行成功了，现在就是有个小问题，
char_dict.json和ord_map.json 有对应关系嘛，因为我现在增广了中文数据，分类需要改，
在想怎么构造训练集
非常感谢您热心的解答

**Comment by MaybeShewill-CV** [comment]
@Crazlion 有对应关系 相互关系就是： 单个字符<==>字符ascii编码<==>字符数字标签 这三者之间的关系

**Comment by mdbenito** [comment]
You may use the available option in write_features.py in order to generate
the charsets from the labels in your dataset. Call the script with --help
for info

**Comment by CMWENLIU** [comment]
@Crazlion 
I'm still struggling on this issue. My packages are installed via pip.
Where is the previous git version?
How did you make it works?
Thank you so much!

**Comment by Crazlion** [comment]
> @Crazlion
> I'm still struggling on this issue. My packages are installed via pip.
> Where is the previous git version?
> How did you make it works?
> Thank you so much!

git check + former version hash
then will go to the version

**Comment by qchenclaire** [comment]
My tensorflow version is 1.3 but still got the notFoundError

> python3 tools/demo_shadownet.py --image_path data/test_images/1.jpg --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
Importing configuration global_configuration.config from .
2018-10-23 16:54:46.360763: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-23 16:54:46.360785: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-23 16:54:46.360793: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-10-23 16:54:46.360801: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-23 16:54:46.360806: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX512F instructions, but these are available on your machine and could speed up CPU computations.
2018-10-23 16:54:46.360811: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Restoring parameters from model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
INFO: 10-23 16:54:46: tf_logging.py:82 * 140540620265216 Restoring parameters from model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
2018-10-23 16:54:46.415682: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization_1/moving_variance not found in checkpoint
2018-10-23 16:54:46.423609: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization/gamma not found in checkpoint
2018-10-23 16:54:46.427791: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization/beta not found in checkpoint
2018-10-23 16:54:46.428039: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization/moving_variance not found in checkpoint
2018-10-23 16:54:46.428166: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization/moving_mean not found in checkpoint
2018-10-23 16:54:46.428573: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization_1/beta not found in checkpoint
2018-10-23 16:54:46.429149: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization_1/moving_mean not found in checkpoint
2018-10-23 16:54:46.429488: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key shadow/batch_normalization_1/gamma not found in checkpoint
Traceback (most recent call last):
  File "/home/qchen/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/qchen/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/qchen/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key shadow/batch_normalization_1/moving_variance not found in checkpoint
	 [[Node: save/RestoreV2_16 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_16/tensor_names, save/RestoreV2_16/shape_and_slices)]]

**Comment by MaybeShewill-CV** [comment]
@qchenclaire The code has been upgraded to tensorflow 1.10

**Comment by qchenclaire** [comment]
> @qchenclaire The code has been upgraded to tensorflow 1.10

Do you have a pre-trained model that could be loaded using tensorflow 1.10?

**Comment by MaybeShewill-CV** [comment]
@qchenclaire Still don't have enough spare time to train a new model==!

**Comment by Rohit-AMARIS** [comment]
I am facing the following issue in docker if i run the Demo. Please let me know if anyone has a solution to this?

python tools/demo_shadownet.py --image_path 1.jpg --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999


Importing configuration global_configuration.config from .
2018-10-30 09:10:33.950449: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-30 09:10:34.052164: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-30 09:10:34.052772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 4.67GiB
2018-10-30 09:10:34.052813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-10-30 09:10:34.308101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-30 09:10:34.308149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-10-30 09:10:34.308218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-10-30 09:10:34.308453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5159 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
INFO: 10-30 09:10:34: tf_logging.py:115 * 140674375792384 Restoring parameters from model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
2018-10-30 09:10:34.989780: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key shadow/batch_normalization/beta not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key shadow/batch_normalization/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_6_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1725, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key shadow/batch_normalization/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_6_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2', defined at:
  File "tools/demo_shadownet.py", line 126, in <module>
    recognize(image_path=args.image_path, cfg=cfg, weights_path=args.weights_path, num_classes=args.num_classes)
  File "tools/demo_shadownet.py", line 99, in recognize
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key shadow/batch_normalization/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_6_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1737, in restore
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 351, in get_tensor
    status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/demo_shadownet.py", line 126, in <module>
    recognize(image_path=args.image_path, cfg=cfg, weights_path=args.weights_path, num_classes=args.num_classes)
  File "tools/demo_shadownet.py", line 105, in recognize
    saver.restore(sess=sess, save_path=weights_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1743, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key shadow/batch_normalization/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_6_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2', defined at:
  File "tools/demo_shadownet.py", line 126, in <module>
    recognize(image_path=args.image_path, cfg=cfg, weights_path=args.weights_path, num_classes=args.num_classes)
  File "tools/demo_shadownet.py", line 99, in recognize
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key shadow/batch_normalization/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_6_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by MaybeShewill-CV** [comment]
@Rohit-AMARIS The pretrained model is not corresponding to the new code. Do not have enough spare time to train a new model. You can train a new one on your own.

**Comment by ZhangZoffy** [comment]
> @Crazlion
读取模型时，我遇到了和你一样的报错。你是怎么解决的？

**Comment by MaybeShewill-CV** [comment]
@ZhangZoffy You may update the repo and test again:)
