### ISSUE TITLE
AssertionError: tfrecords file not found: data/train_feature.tfrecords

### ISSUE THREAD

**Issue by tensor-flower** [MaybeShewill-CV/CRNN_Tensorflow#171]
```
root@6bb9fa755b6e:/app# python3 tools/test_shadownet.py --dataset_dir data/ --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999 --num_classes 37
Importing configuration global_configuration.config from .
Traceback (most recent call last):
  File "tools/test_shadownet.py", line 142, in <module>
    visualize=args.visualize, num_threads=args.num_threads, num_classes=args.num_classes)
  File "tools/test_shadownet.py", line 80, in test_shadownet
    input_images, input_labels, input_image_names = decoder.read_features(cfg, cfg.TEST.BATCH_SIZE, num_threads)
  File "/app/local_utils/data_utils.py", line 217, in read_features
    assert ops.exists(tfrecords_path), "tfrecords file not found: %s" % tfrecords_path
AssertionError: tfrecords file not found: data/train_feature.tfrecords
```

Is that file needed? I'm using docker.

**Comment by MaybeShewill-CV** [comment]
@tensor-flower Yep you can make your own tfrecords

**Comment by tensor-flower** [comment]
#172
