### ISSUE TITLE
Train self data on windows

### ISSUE THREAD

**Issue by wdsd641417025** [MaybeShewill-CV/CRNN_Tensorflow#188]
when I try to train this using my data ,error happened, 
did somebody have train this code  on windows ,Please give me some advice

Traceback (most recent call last):
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[32,32,100,3], <unknown>, [32,1]], output_types=[DT_FLOAT, DT_VARIANT, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train_shadownet.py", line 186, in <module>
    num_threads=args.num_threads)
  File "tools/train_shadownet.py", line 171, in train_shadownet
    _, c, summary = sess.run([optimizer, cost, merge_summary_op])
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[32,32,100,3], <unknown>, [32,1]], output_types=[DT_FLOAT, DT_VARIANT, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "tools/train_shadownet.py", line 186, in <module>
    num_threads=args.num_threads)
  File "tools/train_shadownet.py", line 78, in train_shadownet
    input_images, input_labels, input_image_names = decoder.read_features(cfg, cfg.TRAIN.BATCH_SIZE, num_threads)
  File "D:\thesis_design\textdetection\CRNN_Tensorflow-master\local_utils\data_utils.py", line 231, in read_features
    input_images, input_labels, input_image_names = iterator.get_next()
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 420, in get_next
    name=name)), self._output_types,
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2108, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\sofeware\Anaconda\envs\python3\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[32,32,100,3], <unknown>, [32,1]], output_types=[DT_FLOAT, DT_VARIANT, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

**Comment by kei6** [comment]
@wdsd641417025 Check the size of your training set. Length of training set lower than batch size cause this issue.

**Comment by wdsd641417025** [comment]
> @wdsd641417025 Check the size of your training set. Length of training set lower than batch size cause this issue.

**Comment by wdsd641417025** [comment]
@kei6  thanks a lot! I try it just now and it works well

**Comment by 1810325** [comment]
@wdsd641417025 @kei6 i know i should  Check the size of your training set. Length of training set lower than batch size cause this issue.but how can i change the batch

**Comment by ZOUYIyi** [comment]
> @kei6  thanks a lot! I try it just now and it works well

how to convert raw image to tfrecord ,I got strucked in the mutilprocess problem, could you tell me your solution?
