### ISSUE TITLE
when using my own model to test my data or using pre-model to continue my training ,error happened

### ISSUE THREAD

**Issue by wdsd641417025** [MaybeShewill-CV/CRNN_Tensorflow#190]
when using my own model to test my data or using pre-model to continue my training ,error 

Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "F:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "F:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,547]
         [[{{node save/Assign_8}} = Assign[T=DT_FLOAT, _class=["loc:@shadow/LSTMLayers/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow/LSTMLayers/w, save/RestoreV2/_17)]]

**Comment by MaybeShewill-CV** [comment]
@wdsd641417025 You may check your tensor shape. The repo has beed updated:)
