### ISSUE TITLE
Can you tell how to run your code with a screenshot on your system of the commands you used? I can't find CHAR_DICT_PATH

### ISSUE THREAD

**Issue by sushi997** [MaybeShewill-CV/CRNN_Tensorflow#213]

**Comment by MaybeShewill-CV** [comment]
@sushi997 You may find it in ./data/char_dict folder:)

**Comment by Sanix-Darker** [comment]
Please, what about : MODEL_WEIGHTS or ORD_MAP_PATH

Because i got this error : 
```
Traceback (most recent call last):
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./data/char_dict/char_dict_en.json: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test_shadownet.py", line 166, in <module>
    is_vis=args.visualize
  File "./tools/test_shadownet.py", line 131, in recognize
    saver.restore(sess=sess, save_path=weights_path)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./data/char_dict/char_dict_en.json: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at /home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "./tools/test_shadownet.py", line 166, in <module>
    is_vis=args.visualize
  File "./tools/test_shadownet.py", line 120, in recognize
    saver = tf.train.Saver()
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```
