### ISSUE TITLE
windows multiprocessing error

### ISSUE THREAD

**Issue by opentld** [MaybeShewill-CV/CRNN_Tensorflow#215]
platform:  win10,python3.6,CUDA 9.2
----------------------------------------------------------------------------------------------------------
python ./tools/test_shadownet.py --dataset_dir ./data/test_images --weight_path ./crnn_chinese --char_dict_path ./data/char_dict --ord_map_dict_path ./data/char_dict --process_all 1 --visualize 1

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\SourceCodes\tensorflow\text\CRNN_Tensorflow-master\tools\test_shadownet.py", line 26, in <module>
    from data_provider import tf_io_pipline_fast_tools
  File "E:\SourceCodes\tensorflow\text\CRNN_Tensorflow-master\data_provider\tf_io_pipline_fast_tools.py", line 28, in <module>
    _SAMPLE_INFO_QUEUE = Manager().Queue()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\managers.py", line 513, in start
    self._process.start()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
----------------------------------------------------------------------------------------------------------

anybody knows how to resolve this problem?

**Comment by MaybeShewill-CV** [comment]
fork can not be directly used on windows. You may search it on stackoverflow





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by opentld** [comment]
move   lines 26  'from data_provider import tf_io_pipline_fast_tools'

under 
 if __name__ == '__main__':
    from data_provider import tf_io_pipline_fast_tools

fixed!
