### ISSUE TITLE
crnn_chinese pre_trained model error

### ISSUE THREAD

**Issue by opentld** [MaybeShewill-CV/CRNN_Tensorflow#216]
platform: win10,python3.6,tensorflow 1.12,cuda 9.2
----------------------------------------------------------------------------------------------------------
python ./tools/test_shadownet.py --image_path ./data/test_images/test_01.jpg --weights_path ./crnn_chinese/shadownet.ckpt --char_dict_path ./data/char_dict/char_dict_cn.json --ord_map_dict_path ./data/char_dict/ord_map_cn.json --visualize 1
2019-03-31 15:52:22.760346: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-03-31 15:52:23.663846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.34GiB
2019-03-31 15:52:23.671292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-31 15:52:24.694506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-31 15:52:24.699252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-03-31 15:52:24.701718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-03-31 15:52:24.704662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2457 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
INFO:tensorflow:Restoring parameters from ./crnn_chinese/shadownet.ckpt
I0331 15:52:24.718177 22752 tf_logging.py:115] Restoring parameters from ./crnn_chinese/shadownet.ckpt
Traceback (most recent call last):
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
         [[{{node save/Assign_45}} = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2/_91)]]
         [[{{node save/RestoreV2/_32}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:16)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1546, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
         [[node save/Assign_45 (defined at ./tools/test_shadownet.py:113)  = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2/_91)]]
         [[{{node save/RestoreV2/_32}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:16)]]

Caused by op 'save/Assign_45', defined at:
  File "./tools/test_shadownet.py", line 158, in <module>
    is_vis=args.visualize
  File "./tools/test_shadownet.py", line 113, in recognize
    saver = tf.train.Saver()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1102, in __init__
    self.build()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
         [[node save/Assign_45 (defined at ./tools/test_shadownet.py:113)  = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2/_91)]]
         [[{{node save/RestoreV2/_32}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:16)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test_shadownet.py", line 158, in <module>
    is_vis=args.visualize
  File "./tools/test_shadownet.py", line 124, in recognize
    saver.restore(sess=sess, save_path=weights_path)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1582, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
         [[node save/Assign_45 (defined at ./tools/test_shadownet.py:113)  = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2/_91)]]
         [[{{node save/RestoreV2/_32}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:16)]]

Caused by op 'save/Assign_45', defined at:
  File "./tools/test_shadownet.py", line 158, in <module>
    is_vis=args.visualize
  File "./tools/test_shadownet.py", line 113, in recognize
    saver = tf.train.Saver()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1102, in __init__
    self.build()
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\training\saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "D:\DevelopTools\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
         [[node save/Assign_45 (defined at ./tools/test_shadownet.py:113)  = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2/_91)]]
         [[{{node save/RestoreV2/_32}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:16)]]

----------------------------------------------------------------------------------------------------------
is the crnn_chinese pretrained model wrong?

**Comment by MaybeShewill-CV** [comment]
@opentld You need to change the global_configuration.py file. You may find the answer in that script:)

**Comment by opentld** [comment]
__C.ARCH.SEQ_LENGTH = 70  # cn dataset
#__C.ARCH.SEQ_LENGTH = 25  # synth90k dataset
# Width x height into which training / testing images are resized before feeding into the network
__C.ARCH.INPUT_SIZE = (280, 32)  # cn dataset
#__C.ARCH.INPUT_SIZE = (100, 32)  # synth90k dataset
# Number of channels in images
__C.ARCH.INPUT_CHANNELS = 3
# Number character classes
__C.ARCH.NUM_CLASSES = 5825  # cn dataset
#__C.ARCH.NUM_CLASSES = 37  # synth90k dataset

----------------------------------------------------------------------------------------------------------------deal :)
