### ISSUE TITLE
Get an error when convert the raw data to tfrecord

### ISSUE THREAD

**Issue by aaronjie** [MaybeShewill-CV/CRNN_Tensorflow#245]
environment information
os version: win10
tensorflow version: 1.13.1

error log is following...
-------------------------------------------------------------------------------------------------------
I0506 13:10:17.228113 8860 write_tfrecords.py:682] Start write tensorflow records for train...
Traceback (most recent call last):
  File "tools/write_tfrecords.py", line 1035, in <module>
    save_dir=args.save_dir
  File "tools/write_tfrecords.py", line 1017, in write_tfrecords
    save_dir=save_dir
  File "tools/write_tfrecords.py", line 776, in generate_tfrecords
    tfrecords_writer.run()
  File "tools/write_tfrecords.py", line 698, in run
    process.start()
  File "C:\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle SwigPyObject objects
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by MaybeShewill-CV** [comment]
@aaronjie multiprocess module is a little different between windows and linux. I have not tested the code on windows. You may see #238 which may help you. Welcome to share the solution with others if you've got one:)
