### ISSUE TITLE
Got an error while use test_shadownet in iterative manner

### ISSUE THREAD

**Issue by vaibhavjussspacetech** [MaybeShewill-CV/CRNN_Tensorflow#254]

**Comment by vaibhavjussspacetech** [comment]
Traceback (most recent call last):
  File "tools/text_detection.py", line 115, in <module>
    text = recognize(image, sys_path, count1)
  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/tools/test_shadownet1.py", line 73, in recognize
    reuse=False
  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/crnn_model/crnn_net.py", line 225, in inference
    inputdata=inputdata, name='feature_extraction_module'
  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/crnn_model/crnn_net.py", line 84, in _feature_sequence_extraction
    inputdata=inputdata, out_dims=64, name='conv1'
  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/crnn_model/crnn_net.py", line 62, in _conv_stage
    kernel_size=3, stride=1, use_bias=True, name='conv'
  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/crnn_model/cnn_basenet.py", line 75, in conv2d
    w = tf.get_variable('W', filter_shape, initializer=w_init)
  File "/home/uss/Vaibhav/Virtual_env_python/env/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/home/uss/Vaibhav/Virtual_env_python/env/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/home/uss/Vaibhav/Virtual_env_python/env/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "/home/uss/Vaibhav/Virtual_env_python/env/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/home/uss/Vaibhav/Virtual_env_python/env/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 861, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable shadow_net/feature_extraction_module/conv1/conv/W already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/crnn_model/cnn_basenet.py", line 75, in conv2d
    w = tf.get_variable('W', filter_shape, initializer=w_init)
  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/crnn_model/crnn_net.py", line 62, in _conv_stage
    kernel_size=3, stride=1, use_bias=True, name='conv'
  File "/home/uss/Vaibhav/Virtual_env_python/CRNN_Tensorflow/crnn_model/crnn_net.py", line 84, in _feature_sequence_extraction
    inputdata=inputdata, out_dims=64, name='conv1'

**Comment by MaybeShewill-CV** [comment]
@vaibhavjussspacetech Can not see any helpful information:)

**Comment by vaibhavjussspacetech** [comment]
Thanks for your kind replly.
It was just a matter of set default graph in tensorflow...I find a solution.
