### ISSUE TITLE
How to speed up inference with batch images input ?

### ISSUE THREAD

**Issue by liuchangf** [MaybeShewill-CV/CRNN_Tensorflow#268]
Hello :+1: 
 
  How to speed up inference with batch images input ? 
  When I use test_shadownet.py to inference image , it only can take one image per time , when the image size changed , I have to create a new graph and restore the saved model, it cost a lot of time. 
   Can you please enlighten me for how to use batch inference ?

**Comment by MaybeShewill-CV** [comment]
@liuchangf You may first preprocess all your test images and make them a batch of data and put them into the crnn model then:)

**Comment by liuchangf** [comment]
In the test_shadownet.py , I changed the following code (1 ->None in shape)

inputdata = tf.placeholder(
        dtype=tf.float32,
        shape=[1, new_heigth, new_width, CFG.ARCH.INPUT_CHANNELS],
        name='input'
    )

To

inputdata = tf.placeholder(
        dtype=tf.float32,
        shape=[None, new_heigth, new_width, CFG.ARCH.INPUT_CHANNELS],
        name='input'
    )
but raise an error , I will paste the error later .

And here means new_width may be 100 or bigger , what means element in batch may have different size.

new_width = new_width if new_width > CFG.ARCH.INPUT_SIZE[0] else CFG.ARCH.INPUT_SIZE[0]

So could you please share some ideas with me ? Thanks

**Comment by MaybeShewill-CV** [comment]
@liuchangf If you want to test a batch of data at the same time.You need to make sure they share the same image size yourself:)

**Comment by liuchangf** [comment]
Hello 
   when I create tfrecord with write_tfrecord.py, following error raised:

I0530 17:05:48.741050 1249 shadownet_data_feed_pipline.py:155] Start initialize lexicon information list...
100%|████████████████████████████████████████████████████████████████████████| 11635/11635 [00:00<00:00, 1842649.41it/s]
I0530 17:05:48.749175 1249 shadownet_data_feed_pipline.py:162] Start initialize train sample information list...
100%|██████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 17681.15it/s]
I0530 17:05:49.316560 1249 shadownet_data_feed_pipline.py:177] Start initialize validation sample information list...
100%|████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 16805.79it/s]
I0530 17:05:49.376833 1249 shadownet_data_feed_pipline.py:191] Start initialize testing sample information list...
100%|██████████████████████████████████████████████████████████████████████████████| 635/635 [00:00<00:00, 17019.18it/s]
I0530 17:05:49.414914 1249 shadownet_data_feed_pipline.py:83] Generating training sample tfrecords...
I0530 17:05:49.415189 1249 tf_io_pipline_fast_tools.py:421] Start filling train dataset sample information queue...
  0%|                                                                                         | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "write_tfrecords.py", line 74, in <module>
    save_dir=args.save_dir
  File "write_tfrecords.py", line 60, in write_tfrecords
    save_dir=save_dir
  File "/home/user/PycharmProjects/tf_2019_4_16/code/park_number/CRNN_Tensorflow/data_provider/shadownet_data_feed_pipline.py", line 93, in generate_tfrecords
    dataset_flag='train'
  File "/home/user/PycharmProjects/tf_2019_4_16/code/park_number/CRNN_Tensorflow/data_provider/tf_io_pipline_fast_tools.py", line 413, in __init__
    self._init_example_info_queue()
  File "/home/user/PycharmProjects/tf_2019_4_16/code/park_number/CRNN_Tensorflow/data_provider/tf_io_pipline_fast_tools.py", line 430, in _init_example_info_queue
    encoded_label, _ = self.encode_labels(lexicon_label)
  File "/home/user/PycharmProjects/tf_2019_4_16/code/park_number/CRNN_Tensorflow/data_provider/tf_io_pipline_fast_tools.py", line 211, in encode_labels
    encode_label = [self.char_to_int(char) for char in label]
  File "/home/user/PycharmProjects/tf_2019_4_16/code/park_number/CRNN_Tensorflow/data_provider/tf_io_pipline_fast_tools.py", line 211, in <listcomp>
    encode_label = [self.char_to_int(char) for char in label]
  File "/home/user/PycharmProjects/tf_2019_4_16/code/park_number/CRNN_Tensorflow/data_provider/tf_io_pipline_fast_tools.py", line 184, in char_to_int
    result = int(self._ord_map[str_key])
ValueError: invalid literal for int() with base 10: 'd'




Do you have any ideas?  Thank you

**Comment by liuchangf** [comment]
But I found  in char_dict_en.json

{
    "100_ord": "d",
    "101_ord": "e",
    "102_ord": "f",

and ord_map_en.json
{
    "0_index": "54",
    "100_ord": "8",
    "101_ord": "20",

The dict contain 'd' , I'm confused

**Comment by liuchangf** [comment]
I create tf record us following command:

python tools/write_tfrecords.py \
--dataset_dir /media/user/新加卷/park_number_for_training \
--save_dir /media/user/新加卷/park_number_for_training \
--ord_map_dict_path data/char_dict/char_dict_en.json \
--char_dict_path data/char_dict/ord_map_en.json

**Comment by MaybeShewill-CV** [comment]
@liuchangf You use the wrong char dict path and ord map file path. Please check carefully:)

**Comment by liuchangf** [comment]
I found these 2 agrs just let it be .

**Comment by liuchangf** [comment]
Good Day :

If I keep training on pre-trained model , but with my own data , which char dict should use ? The char dict for pre-trained model or the new char dict which generated by my own data ?

     Thanks for your kindly reply

**Comment by MaybeShewill-CV** [comment]
@liuchangf If your dataset contains some character that doesn't appear in existed char dict file then you should use your own and you may reuse the existed char dict file otherwise:)

**Comment by liuchangf** [comment]
Hello 

When I training , an error raised "InvalidArgumentError (see above for traceback): Labels length is zero in batch 4"  detail info as follows . Could you please share your ideas with me ?  Thank you.

         (venv) user@user-System-Product-Name:~/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master$ sh train.sh 
I0531 17:46:26.677819 8248 font_manager.py:542] Could not open font file /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.
I0531 17:46:28.531959 8248 font_manager.py:1341] generated new fontManager
I0531 17:46:28.730984 8248 train_shadownet.py:569] Use single gpu to train the model
WARNING:tensorflow:From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
W0531 17:46:28.926344 8248 deprecation.py:323] From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/cnn_basenet.py:332: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
W0531 17:46:28.933082 8248 deprecation.py:323] From /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/cnn_basenet.py:332: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
WARNING:tensorflow:From /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/crnn_net.py:171: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
W0531 17:46:29.163199 8248 deprecation.py:323] From /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/crnn_net.py:171: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/rnn.py:233: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
W0531 17:46:29.164894 8248 deprecation.py:323] From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/rnn.py:233: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
WARNING:tensorflow:From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:443: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0531 17:46:29.165701 8248 deprecation.py:323] From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:443: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/cnn_basenet.py:280: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0531 17:46:29.731986 8248 deprecation.py:506] From /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/cnn_basenet.py:280: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-05-31 17:46:31.967220: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-31 17:46:32.066729: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-31 17:46:32.067354: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x437dd00 executing computations on platform CUDA. Devices:
2019-05-31 17:46:32.067375: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2019-05-31 17:46:32.088954: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2019-05-31 17:46:32.089361: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x452a5b0 executing computations on platform Host. Devices:
2019-05-31 17:46:32.089377: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-31 17:46:32.089732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:01:00.0
totalMemory: 7.76GiB freeMemory: 6.33GiB
2019-05-31 17:46:32.089750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-31 17:46:32.090384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-31 17:46:32.090397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-05-31 17:46:32.090403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-05-31 17:46:32.090621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7154 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
I0531 17:46:32.284291 8248 train_shadownet.py:272] Restore model from model/shadownet.ckpt
WARNING:tensorflow:From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0531 17:46:32.284610 8248 deprecation.py:323] From /home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from model/shadownet.ckpt
I0531 17:46:32.287180 8248 saver.py:1270] Restoring parameters from model/shadownet.ckpt
2019-05-31 17:46:34.100103: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-05-31 17:46:37.595460: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.24G (3474331904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.596363: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.91G (3126898688 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.596904: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.62G (2814208768 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.597524: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.36G (2532787712 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.597539: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-05-31 17:46:37.598150: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.24G (3474331904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.598163: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-05-31 17:46:37.750513: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.24G (3474331904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.750599: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-05-31 17:46:37.752452: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.24G (3474331904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.752485: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-05-31 17:46:37.788323: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.24G (3474331904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.788355: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.13GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-05-31 17:46:37.788906: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 3.24G (3474331904 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-31 17:46:37.788919: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.13GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
I0531 17:46:37.940031 8248 train_shadownet.py:324] Epoch_Train: 705003 cost= 30.484642
I0531 17:46:38.011242 8248 train_shadownet.py:324] Epoch_Train: 705004 cost= 30.355679
2019-05-31 17:46:38.056003: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at ctc_loss_op.cc:168 : Invalid argument: Labels length is zero in batch 4
Traceback (most recent call last):
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Labels length is zero in batch 4
         [[{{node CTCLoss_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_shadownet.py", line 575, in <module>
    need_decode=args.decode_outputs
  File "train_shadownet.py", line 321, in train_shadownet
    [optimizer, train_ctc_loss, merge_summary_op])
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Labels length is zero in batch 4
         [[node CTCLoss_1 (defined at /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/crnn_net.py:255) ]]

Caused by op 'CTCLoss_1', defined at:
  File "train_shadownet.py", line 575, in <module>
    need_decode=args.decode_outputs
  File "train_shadownet.py", line 193, in train_shadownet
    reuse=True
  File "/home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/crnn_net.py", line 255, in compute_loss
    sequence_length=CFG.ARCH.SEQ_LENGTH * np.ones(CFG.TRAIN.BATCH_SIZE)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/ops/ctc_ops.py", line 169, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 323, in ctc_loss
    name=name)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/user/PycharmProjects/CRNN_training/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Labels length is zero in batch 4
         [[node CTCLoss_1 (defined at /home/user/PycharmProjects/CRNN_training/code/CRNN_Tensorflow-master/crnn_model/crnn_net.py:255) ]]

**Comment by MaybeShewill-CV** [comment]
@liuchangf out of memory reduce batch size and test again:)

**Comment by liuchangf** [comment]
Thanks for your reply ,  how many GPU memory do you have when you run batch size=32 ？ I have 8G

**Comment by MaybeShewill-CV** [comment]
@MaybeShewill-CV I use two gtx 1070 which has 8G memory in my local pc:)

**Comment by liuchangf** [comment]
I see ,  batch size should be 16

**Comment by liuchangf** [comment]
Your batch size=32 means ,16 for each GPU？

**Comment by MaybeShewill-CV** [comment]
@liuchangf 32 for each

**Comment by liuchangf** [comment]
Hello 

I found __C.TRAIN.VAL_DISPLAY_STEP = 1000 in global config , but no val information show up during training , I missed something somewhere ?

**Comment by MaybeShewill-CV** [comment]
@liuchangf not all the config params are used:)
