### ISSUE TITLE
python write_tfrecords.py 出错

### ISSUE THREAD

**Issue by xiaohang96** [MaybeShewill-CV/CRNN_Tensorflow#320]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\code\imageAndVideo\CRNN_Tensorflow-master\CRNN_Tensorflow-master\tools\write_tfrecords.py", line 18, in <module>
    from data_provider import shadownet_data_feed_pipline
  File "E:\code\imageAndVideo\CRNN_Tensorflow-master\CRNN_Tensorflow-master\data_provider\shadownet_data_feed_pipline.py", line 23, in <module>
    from data_provider import tf_io_pipline_fast_tools
  File "E:\code\imageAndVideo\CRNN_Tensorflow-master\CRNN_Tensorflow-master\data_provider\tf_io_pipline_fast_tools.py", line 28, in <module>
    _SAMPLE_INFO_QUEUE = Manager().Queue()
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\managers.py", line 543, in start
    self._process.start()
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\GZS13406\AppData\Local\Continuum\anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

请问我这个错误要怎么改正呢，是因为Windows下多线程有问题吗

**Comment by ElegyTsai** [comment]
几天前也碰到这个问题 windows下的Multiprocess运行机制和Linux有点不同，把代码改成单线程或者换linux环境吧

**Comment by MaybeShewill-CV** [comment]
@xiaohang96 查看前面的issue 有相关的解决方案:)
