### ISSUE TITLE
我用了90k的那个模型报错

### ISSUE THREAD

**Issue by ZhangZoffy** [MaybeShewill-CV/CRNN_Tensorflow#359]
https://www.dropbox.com/sh/y4eaunamardibnd/AAB4h8NkakASDoc6Ek4knEGIa?dl=0，从这个地址下载的模型，运行时restore报错。

 Could not open ./crnn_synth90k: Failed precondition: crnn_synth90k; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2019-10-18 11:10:32.837191: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./crnn_synth90k: Failed precondition: crnn_synth90k; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2019-10-18 11:10:32.837242: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_tensor.cc:175 : Data loss: Unable to open table file ./crnn_synth90k: Failed precondition: crnn_synth90k; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/home/service/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/service/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/service/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./crnn_synth90k: Failed precondition: crnn_synth90k; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2}}]]

**Comment by MaybeShewill-CV** [comment]
@ZhangZoffy 对照readme仔细检查你的调用命令行吧:)

**Comment by ZhangZoffy** [comment]
> @ZhangZoffy 对照readme仔细检查你的调用命令行吧:)

python tools/test_shadownet.py --image_path data/test_images/test_01.jpg --weights_path crnn_synth90k --char_dict_path data/char_dict/char_dict_en.json --ord_map_dict_path data/char_dict/ord_map_en.json

我是这么写的，crnn_synth90k文件夹里是下载的模型
![image](https://user-images.githubusercontent.com/28424232/67071277-b1bef580-f1b4-11e9-94a9-7ec7e42fb2cc.png)

**Comment by ZhangZoffy** [comment]
> @ZhangZoffy 对照readme仔细检查你的调用命令行吧:)

![image](https://user-images.githubusercontent.com/28424232/67071361-e763de80-f1b4-11e9-8402-60ff20d586b2.png)
这是模型文件夹里的文件

**Comment by ZhangZoffy** [comment]
解决了，谢谢您~
