### ISSUE TITLE
Can you provide a real example command for MODEL_WEIGHTS_PATH please ?

### ISSUE THREAD

**Issue by Sanix-Darker** [MaybeShewill-CV/CRNN_Tensorflow#361]
i have downloaded the `crnn_synth90k.zip`

And i tried this:
```
python ./tools/test_shadownet.py --image_path ./data/test_images/test_01.jpg --weights_path ./model/crnn_synth90k/checkpoint    --char_dict_path ./data/char_dict/char_dict_en.json    --ord_map_dict_path ./data/char_dict/ord_map_en.json
```

And i got this : 
```
2019-10-21 06:20:26.476474: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_tensor.cc:175 : Data loss: Unable to open table file ./model/crnn_synth90k/checkpoint: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./model/crnn_synth90k/checkpoint: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test_shadownet.py", line 166, in <module>
    is_vis=args.visualize
  File "./tools/test_shadownet.py", line 131, in recognize
    saver.restore(sess=sess, save_path=weights_path)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./model/crnn_synth90k/checkpoint: Data loss: file is too short to be an sstable: perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at /home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "./tools/test_shadownet.py", line 166, in <module>
    is_vis=args.visualize
  File "./tools/test_shadownet.py", line 120, in recognize
    saver = tf.train.Saver()
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by MaybeShewill-CV** [comment]
@Sanix-Darker You may google how to restore model weights from ckpt file:)

**Comment by Sanix-Darker** [comment]
@MaybeShewill-CV am just asking the right command or where am i doing a mistake, i allready done the restore stuff :
```
......
1021 06:41:07.304742 140138077304576 deprecation.py:323] From restore.py:50: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

W1021 06:41:07.335115 140138077304576 module_wrapper.py:139] From restore.py:54: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

W1021 06:41:07.803659 140138077304576 module_wrapper.py:139] From restore.py:85: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-21 06:41:07.803981: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-10-21 06:41:07.804006: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-10-21 06:41:07.804029: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (moonlight): /proc/driver/nvidia/version does not exist
2019-10-21 06:41:07.804269: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-21 06:41:07.832007: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2019-10-21 06:41:07.832330: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55bd4f023980 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-21 06:41:07.832365: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
W1021 06:41:07.834796 140138077304576 module_wrapper.py:139] From restore.py:87: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

Epoch 0, batch 0 | Sample value: [-0.3264256  -0.10616732  0.05325492  0.02422096 -0.1936119 ]
Epoch 0, batch 1 | Sample value: [ 0.00268194  0.10606147  0.1124137  -0.46436003 -0.11036695]
Epoch 1, batch 0 | Sample value: [-0.37493882 -0.13898864  0.04792935 -0.04522546  0.05241241]
Epoch 1, batch 1 | Sample value: [-0.06386025  0.17821224  0.00745429 -0.46784598 -0.02344606]
Epoch 2, batch 0 | Final inference | Sample value: [-0.45343184 -0.15674785  0.03072274 -0.100701    0.2717936 ]
Epoch 2, batch 1 | Final inference | Sample value: [-0.10623933  0.2109501  -0.04515782 -0.47277197  0.02889376]

Saving...
W1021 06:41:08.529299 140138077304576 deprecation.py:323] From restore.py:128: simple_save (from tensorflow.python.saved_model.simple_save) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.
W1021 06:41:08.529525 140138077304576 deprecation.py:323] From /home/darker/.conda/envs/tests/lib/python3.7/site-packages/tensorflow_core/python/saved_model/signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
Ok

Restoring...
W1021 06:41:08.806015 140138077304576 deprecation.py:323] From restore.py:140: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
Ok
Restored values:  [-0.45343184 -0.15674785  0.03072274 -0.100701    0.2717936 ]
Restored values:  [-0.10623933  0.2109501  -0.04515782 -0.47277197  0.02889376]

Inferences match:  True
```

But how to launch my script, or which parameter do i need to pass to `weights_path` ?

**Comment by MaybeShewill-CV** [comment]
@Sanix-Darker Check this https://stackoverflow.com/questions/33759623/tensorflow-how-to-save-restore-a-model

**Comment by Sanix-Darker** [comment]
@MaybeShewill-CV Thank you very much for the reply, but i allready done it.

What i am asking is : what is the parameter i need to place after `weights_path` ???

This is my command : 

```
python ./tools/test_shadownet.py 
--image_path ./data/test_images/test_01.jpg 
--weights_path  ???????????????????????????????? 
--char_dict_path ./data/char_dict/char_dict_en.json    
--ord_map_dict_path ./data/char_dict/ord_map_en.json
```

i don't know if you understand my problem...., if yes, please Help ....

This is my tree's directory:
```
├── config
│   ├── global_config.py
│   ├── __init__.py
├── _config.yml
├── crnn_model
│   ├── cnn_basenet.py
│   ├── crnn_net.py
│   ├── __init__.py
├── crnn_synth90k.zip
├── crnntf-env.yml
├── data
│   ├── char_dict
│   │   ├── char_dict_cn.json
│   │   ├── char_dict_en.json
│   │   ├── ord_map_cn.json
│   │   └── ord_map_en.json
│   ├── images
│   └── test_images
├── data_provider
│   ├── __init__.py
│   ├── shadownet_data_feed_pipline.py
│   └── tf_io_pipline_fast_tools.py
├── __init__.py
├── LICENSE
├── local_utils
│   ├── establish_char_dict.py
│   ├── evaluation_tools.py
│   ├── __init__.py
│   ├── log_utils.py
├── model
│   ├── crnn_syn90k
│   │   ├── saved_model.pb
│   │   └── variables
│   │       ├── variables.data-00000-of-00001
│   │       └── variables.index
│   ├── crnn_syn90k_saved_model
│   │   └── 1
│   │       ├── saved_model.pb
│   │       └── variables
│   │           ├── variables.data-00000-of-00001
│   │           └── variables.index
│   ├── crnn_synth90k
│   │   ├── checkpoint
│   │   ├── crnn_synth90k
│   │   ├── shadownet.ckpt.data-00000-of-00001
│   │   ├── shadownet.ckpt.index
│   │   └── shadownet.ckpt.meta
│   └── crnn_synth90k.zip
├── README.md
├── requirements.txt
├── restore.py
├── tfserve
│   ├── crnn_python_client_via_grpc.py
│   ├── crnn_python_client_via_request.py
│   ├── export_crnn_saved_model.sh
│   ├── export_saved_model.py
│   └── run_tfserve_crnn_gpu.sh
└── tools
    ├── apply_ocr_pdf.py
    ├── evaluate_shadownet.py
    ├── __init__.py
    ├── recongnize_chinese_pdf.py
    ├── test_shadownet.py
    ├── train_shadownet.py
    └── write_tfrecords.py
```

**Comment by Sanix-Darker** [comment]
AAHHH, it's OK, now, thanks, so the complete command is :

```
python ./tools/test_shadownet.py 
--image_path ./data/test_images/test_01.jpg 
--weights_path ./model/crnn_synth90k/shadownet.ckpt    
--char_dict_path ./data/char_dict/char_dict_en.json    
--ord_map_dict_path ./data/char_dict/ord_map_en.json
```

That's what i was asking :smile: 
Thank's for sharing this project !

**Comment by MaybeShewill-CV** [comment]
@Sanix-Darker Once you know how to restore the model weights from a ckpt file you will know what the correct command should:)

**Comment by padmareddy21** [comment]
> AAHHH, it's OK, now, thanks, so the complete command is :
> 
> ```
> python ./tools/test_shadownet.py 
> --image_path ./data/test_images/test_01.jpg 
> --weights_path ./model/crnn_synth90k/shadownet.ckpt    
> --char_dict_path ./data/char_dict/char_dict_en.json    
> --ord_map_dict_path ./data/char_dict/ord_map_en.json
> ```
> 
> That's what i was asking 😄
> Thank's for sharing this project !

**Comment by padmareddy21** [comment]
> AAHHH, it's OK, now, thanks, so the complete command is :
> 
> ```
> python ./tools/test_shadownet.py 
> --image_path ./data/test_images/test_01.jpg 
> --weights_path ./model/crnn_synth90k/shadownet.ckpt    
> --char_dict_path ./data/char_dict/char_dict_en.json    
> --ord_map_dict_path ./data/char_dict/ord_map_en.json
> ```
> 
> That's what i was asking 😄
> Thank's for sharing this project !

How did u get this /model/crnn_synth90k/shadownet.ckpt
