### ISSUE TITLE
recongnize_chinese_pdf.py报错

### ISSUE THREAD

**Issue by zhu2bowen** [MaybeShewill-CV/CRNN_Tensorflow#443]
使用权重模型https://www.dropbox.com/sh/z22xsn4byddalv3/AAAiIxAHJKbqy44M73ow5znSa?dl=0，测试recongnize_chinese_pdf.py。发现加载权重出现报错：
0415 15:14:21.857890 5116 saver.py:1284] Restoring parameters from D:\develop\crnn_tensorflow\pretrained_models\crnn_chinese\shadownet.ckpt-322000
Traceback (most recent call last):
  File "D:\develop\crnn_tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "D:\develop\crnn_tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "D:\develop\crnn_tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
         [[{{node save/Assign_45}}]]

**Comment by zhu2bowen** [comment]
个人问题，没有重新配置global_config.py
